
services:
  agent-server:
    build: .
    image: agent-server:latest
    container_name: agent-server
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./config:/app/config:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
      # Configure chat API endpoint (update as needed for your setup)
      - CHAT_API_BASE_URL=http://host.docker.internal:4000
      # Optional: API key for chat service
      # - CHAT_API_KEY=your-api-key-here
    restart: unless-stopped
    